# Generated by Django 2.2.7 on 2019-11-28 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Familiar',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellidos', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('parentesco', models.CharField(max_length=100, verbose_name='Parentesco')),
            ],
        ),
        migrations.CreateModel(
            name='Informe',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_informe', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Residente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellidos', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('fecha_nacimiento', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ParteInforme',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('SANTIARIA', 'Santiaria'), ('FUNCIONAL', 'Santiaria'), ('PSIQUICA', 'Santiaria'), ('SOCIAL', 'Santiaria'), ('TERAPIA', 'Santiaria'), ('OCUPACIONAL', 'Santiaria')], default='SANTIARIA', max_length=12)),
                ('valoracion_inical', models.CharField(max_length=100, verbose_name='Valoración Inicial')),
                ('objetivos', models.CharField(max_length=100, verbose_name='Objetivos')),
                ('informe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residencias.Informe')),
            ],
        ),
    ]
