# Generated by Django 2.2.7 on 2019-11-28 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residencias', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parteinforme',
            old_name='valoracion_inical',
            new_name='valoracion_inicial',
        ),
        migrations.AlterField(
            model_name='residente',
            name='fecha_nacimiento',
            field=models.DateField(),
        ),
    ]
