# Generated by Django 2.2.7 on 2019-11-28 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residencias', '0003_auto_20191128_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parteinforme',
            name='tipo',
            field=models.CharField(choices=[('SANTIARIA', 'Santiaria'), ('FUNCIONAL', 'Funcional'), ('PSIQUICA', 'Psiquica'), ('SOCIAL', 'Social'), ('TERAPIA', 'Terapia'), ('OCUPACIONAL', 'Ocupacional')], default='SANTIARIA', max_length=12),
        ),
    ]
